# Makefile for TB-CPA program
#--------------------------------------------------------------------------
# Defaults
#--------------------------------------------------------------------------
MAKE = make
F90 = ifort
F90_OPTS = -O3
OMP = -openmp
MKL = -I$(MKLROOT)/include/intel64/lp64 -mkl=parallel
FFLAGS = $(F90_OPTS) $(MKL) $(OMP)

SRC_modules = global.f90

SRC_cpa = bisect.f90 calcSig.f90 ccrlu.f90 clubk.f90 cpaDOS.f90 \
	cpagen.f90 falsi.f90 fixpt.f90 kpts.f90 greens.f90 mainn.f90 \
	newton.f90 readin.f90 readSec.f90 setInitHam.f90 setHam.f90 \
	setOnsites.f90 simp.f90
#greens_omp.f90
#	kpts.f90 mainn.f90 readin.f90 readSec.f90 setHam.f90 \

SRC_omp = cmplxInv.f90 #greens_omp.f90

SRC = $(SRC_modules) $(SRC_cpa) $(SRC_omp)

OBJ_omp = $(SRC_omp:.f90=.o)
$(OBJ_omp): F90_OPTS+=$(OMP)
OBJ = $(SRC:.f90=.o)
EXE = cpaFeSe

#--------------------------------------------------------------------------
# Suffix rules
#--------------------------------------------------------------------------
.SUFFIXES: .o .f90
.f90.o:
	$(F90) $(F90_OPTS) -warn-all -c $<

#--------------------------------------------------------------------------
# Targets
#--------------------------------------------------------------------------
cpaTB:	$(OBJ)
	$(F90) $(FFLAGS) -o $(EXE) $(OBJ)

all:	cpaTB

clean:
	rm -f *.o *.mod *__genmod.f90 $(EXE)
